# Generated by Selenium IDE
import pytest
import time
import json
import csv
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContactus():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def save_result_to_csv(self, test_name, result, message):
        # Append test results to a CSV file
        with open('test_results.csv', mode='a', newline='') as file:
            writer = csv.writer(file)
            writer.writerow([test_name, result, message])

    def test_contactus(self):
        test_name = "Contact Us Page Test"
        try:
            self.driver.get("https://smoothmaths.co.uk/")
            self.driver.set_window_size(1296, 696)
            self.driver.execute_script("window.scrollTo(0,390)")
            self.driver.execute_script("window.scrollTo(0,2384)")
            self.driver.find_element(By.LINK_TEXT, "Contact us").click()
            self.driver.execute_script("window.scrollTo(0,155.3333282470703)")
            self.driver.find_element(By.ID, "et_pb_contact_name_0").click()
            self.driver.find_element(By.ID, "et_pb_contact_name_0").send_keys("Hanzila")
            self.driver.find_element(By.ID, "et_pb_contact_email_0").click()
            self.driver.find_element(By.ID, "et_pb_contact_email_0").send_keys("hanzila@dovidigital.com")
            self.driver.find_element(By.ID, "et_pb_contact_message_0").click()
            self.driver.execute_script("window.scrollTo(0,428)")
            self.driver.find_element(By.ID, "et_pb_contact_message_0").send_keys("Testing")
            self.driver.find_element(By.NAME, "et_pb_contact_captcha_0").click()
            self.driver.find_element(By.NAME, "et_pb_contact_captcha_0").send_keys("19")
            self.driver.find_element(By.NAME, "et_builder_submit_button").click()

            # Wait for confirmation message
            confirmation_message = WebDriverWait(self.driver, 10).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, ".et_pb_contact_form_0.et_pb_contact_form_container.clearfix"))
            )
            
            # Verify if the expected confirmation text appears
            if "Thanks for contacting us" in confirmation_message.text:
                result = "Pass"
                message = "Contact form submission successful."
            else:
                result = "Fail"
                message = "Confirmation message not found."
            
            # Save result to CSV
            self.save_result_to_csv(test_name, result, message)
        
        except Exception as e:
            result = "Fail"
            message = str(e)
            self.save_result_to_csv(test_name, result, message)
            raise

